"""inventory: units, items, locations, stock ledger, batches, recipes

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-22 04:18:30.165289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_categories_name'))
    )
    op.create_table('units_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('factor_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('factor_to_base > 0', name=op.f('ck_units_of_measure_positive_factor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units_of_measure')),
    sa.UniqueConstraint('code', name=op.f('uq_units_of_measure_code'))
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('stock_unit_id', sa.Integer(), nullable=False),
    sa.Column('track_batches', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Numeric(precision=16, scale=4), server_default='0', nullable=False),
    sa.Column('max_stock', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=16, scale=4), server_default='0', nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_type in ('raw_material','ingredient','semi_finished','finished_product','packaging')", name=op.f('ck_inventory_items_valid_item_type')),
    sa.CheckConstraint('min_stock >= 0', name=op.f('ck_inventory_items_min_stock_nonneg')),
    sa.CheckConstraint('reorder_level >= 0', name=op.f('ck_inventory_items_reorder_nonneg')),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], name=op.f('fk_inventory_items_category_id_inventory_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_unit_id'], ['units_of_measure.id'], name=op.f('fk_inventory_items_stock_unit_id_units_of_measure'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_inventory_items_sku'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_items_category_id', ['category_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('location_type', sa.String(length=20), server_default='store', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location_type in ('warehouse','kitchen','store','bar')", name=op.f('ck_locations_valid_location_type')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_locations_branch_id_branches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('branch_id', 'name', name='uq_location_branch_name')
    )
    op.create_table('item_packaging_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('factor_to_stock_unit', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.CheckConstraint('factor_to_stock_unit > 0', name=op.f('ck_item_packaging_units_positive_packaging_factor')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_item_packaging_units_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_packaging_units')),
    sa.UniqueConstraint('item_id', 'name', name='uq_item_packaging_name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=16, scale=4), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('yield_qty > 0', name=op.f('ck_recipes_positive_yield')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_recipes_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('item_id', name=op.f('uq_recipes_item_id'))
    )
    op.create_table('stock_balances',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=16, scale=4), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_balances_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_balances_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id', 'location_id', name=op.f('pk_stock_balances'))
    )
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty_remaining <= qty_received', name=op.f('ck_stock_batches_batch_remaining_le_received')),
    sa.CheckConstraint('qty_remaining >= 0', name=op.f('ck_stock_batches_batch_remaining_nonneg')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_batches_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_batches_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_batches'))
    )
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index('ix_stock_batches_fifo', ['item_id', 'location_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_location_id'), ['location_id'], unique=False)

    op.create_table('recipe_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_recipe_lines_positive_recipe_qty')),
    sa.ForeignKeyConstraint(['ingredient_item_id'], ['inventory_items.id'], name=op.f('fk_recipe_lines_ingredient_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_lines_recipe_id_recipes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units_of_measure.id'], name=op.f('fk_recipe_lines_unit_id_units_of_measure'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_lines')),
    sa.UniqueConstraint('recipe_id', 'ingredient_item_id', name='uq_recipe_ingredient')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("movement_type in ('opening', 'adjustment_in', 'adjustment_out', 'transfer_in', 'transfer_out', 'consumption', 'wastage', 'purchase_in', 'purchase_return')", name=op.f('ck_stock_movements_valid_movement_type')),
    sa.CheckConstraint('new_balance >= 0', name=op.f('ck_stock_movements_balance_nonneg')),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], name=op.f('fk_stock_movements_batch_id_stock_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_movements_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_movements_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_movements_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_movements_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_stock_movements_item_loc', ['item_id', 'location_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_location_id'), ['location_id'], unique=False)


    # stock_movements is an append-only ledger, like audit_logs: reject UPDATE and DELETE.
    op.execute("""
        CREATE TRIGGER trg_stock_movements_immutable
        BEFORE UPDATE OR DELETE ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable();
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP TRIGGER IF EXISTS trg_stock_movements_immutable ON stock_movements')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_location_id'))
        batch_op.drop_index('ix_stock_movements_item_loc')
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_branch_id'))

    op.drop_table('stock_movements')
    op.drop_table('recipe_lines')
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_batches_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_item_id'))
        batch_op.drop_index('ix_stock_batches_fifo')

    op.drop_table('stock_batches')
    op.drop_table('stock_balances')
    op.drop_table('recipes')
    op.drop_table('item_packaging_units')
    op.drop_table('locations')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_items_category_id')

    op.drop_table('inventory_items')
    op.drop_table('units_of_measure')
    op.drop_table('inventory_categories')
    # ### end Alembic commands ###
