"""purchasing: suppliers, purchase orders, receiving, invoices, payments, ledger, returns

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-22 10:59:38.171389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('payment_terms_days >= 0', name=op.f('ck_suppliers_terms_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    op.create_table('supplier_balances',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_balances_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_id', name=op.f('pk_supplier_balances'))
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('order_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('draft', 'submitted', 'approved', 'rejected', 'partially_received', 'received', 'cancelled')", name=op.f('ck_purchase_orders_valid_po_status')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_purchase_orders_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_purchase_orders_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_orders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_purchase_orders_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_orders_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('ix_purchase_orders_supplier_id', ['supplier_id'], unique=False)

    op.create_table('supplier_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=60), nullable=True),
    sa.Column('last_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_supplier_items_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_items_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_items')),
    sa.UniqueConstraint('supplier_id', 'item_id', name='uq_supplier_item')
    )
    op.create_table('supplier_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("entry_type in ('invoice', 'payment', 'return', 'adjustment', 'opening')", name=op.f('ck_supplier_ledger_entries_valid_ledger_entry_type')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_supplier_ledger_entries_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_ledger_entries_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_supplier_ledger_entries_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_ledger_entries'))
    )
    with op.batch_alter_table('supplier_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_ledger_entries_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='unpaid', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('unpaid', 'partial', 'paid')", name=op.f('ck_purchase_invoices_valid_invoice_status')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_purchase_invoices_invoice_total_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_purchase_invoices_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_invoices_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_purchase_invoices_po_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_invoices_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_invoices')),
    sa.UniqueConstraint('supplier_id', 'invoice_number', name='uq_supplier_invoice_number')
    )
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_invoices_branch_id', ['branch_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('packaging_unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=16, scale=4), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('quantity_ordered > 0', name=op.f('ck_purchase_order_lines_positive_qty_ordered')),
    sa.CheckConstraint('quantity_received <= quantity_ordered', name=op.f('ck_purchase_order_lines_qty_received_le_ordered')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_purchase_order_lines_qty_received_nonneg')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_purchase_order_lines_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['packaging_unit_id'], ['item_packaging_units.id'], name=op.f('fk_purchase_order_lines_packaging_unit_id_item_packaging_units'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_po_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines'))
    )
    op.create_table('purchase_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_purchase_receipts_po_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_purchase_receipts_received_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_receipts'))
    )
    op.create_table('purchase_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_purchase_returns_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_returns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_purchase_returns_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_purchase_returns_po_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_returns_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_returns'))
    )
    op.create_table('purchase_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_receipt_lines_positive_receipt_qty')),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], name=op.f('fk_purchase_receipt_lines_po_line_id_purchase_order_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], name=op.f('fk_purchase_receipt_lines_receipt_id_purchase_receipts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_receipt_lines'))
    )
    op.create_table('purchase_return_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_return_lines_positive_return_qty')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_purchase_return_lines_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['purchase_returns.id'], name=op.f('fk_purchase_return_lines_return_id_purchase_returns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_return_lines'))
    )
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), server_default='cash', nullable=False),
    sa.Column('paid_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_supplier_payments_positive_payment_amount')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_supplier_payments_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], name=op.f('fk_supplier_payments_invoice_id_purchase_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_supplier_payments_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_payments_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_payments'))
    )

    # supplier_ledger_entries is an append-only ledger, like audit_logs and stock_movements.
    op.execute("""
        CREATE TRIGGER trg_supplier_ledger_entries_immutable
        BEFORE UPDATE OR DELETE ON supplier_ledger_entries
        FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable();
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP TRIGGER IF EXISTS trg_supplier_ledger_entries_immutable ON supplier_ledger_entries')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_payments')
    op.drop_table('purchase_return_lines')
    op.drop_table('purchase_receipt_lines')
    op.drop_table('purchase_returns')
    op.drop_table('purchase_receipts')
    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_invoices_branch_id')

    op.drop_table('purchase_invoices')
    with op.batch_alter_table('supplier_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_ledger_entries_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_ledger_entries_created_at'))

    op.drop_table('supplier_ledger_entries')
    op.drop_table('supplier_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_orders_supplier_id')
        batch_op.drop_index('ix_purchase_orders_branch_id')

    op.drop_table('purchase_orders')
    op.drop_table('supplier_balances')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
