"""POS: floors, tables, customers, modifiers, orders, invoices, payments, cash register

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 05:11:25.554233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_floors_branch_id_branches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors')),
    sa.UniqueConstraint('branch_id', 'name', name='uq_floor_branch_name')
    )
    op.create_table('cash_register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counted_cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('open', 'closed')", name=op.f('ck_cash_register_sessions_valid_cash_session_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_cash_register_sessions_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_cash_register_sessions_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_cash_register_sessions_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], name=op.f('fk_cash_register_sessions_opened_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_register_sessions'))
    )
    op.create_table('product_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_product_modifiers_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_modifiers')),
    sa.UniqueConstraint('item_id', 'name', name='uq_modifier_item_name')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='2', nullable=False),
    sa.Column('status', sa.String(length=12), server_default='available', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('available', 'occupied', 'reserved', 'cleaning')", name=op.f('ck_tables_valid_table_status')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_tables_positive_capacity')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_tables_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_tables_floor_id_floors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables')),
    sa.UniqueConstraint('floor_id', 'name', name='uq_table_floor_name')
    )
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("movement_type in ('opening', 'cash_in', 'cash_out', 'sale', 'closing_count')", name=op.f('ck_cash_movements_valid_cash_movement_type')),
    sa.ForeignKeyConstraint(['session_id'], ['cash_register_sessions.id'], name=op.f('fk_cash_movements_session_id_cash_register_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cash_movements_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_movements'))
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_session_id'), ['session_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discount_kind', sa.String(length=10), server_default='none', nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount_reason', sa.String(length=255), nullable=True),
    sa.Column('delivery_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_kind in ('none', 'percentage', 'fixed')", name=op.f('ck_orders_valid_discount_kind')),
    sa.CheckConstraint("order_type in ('dine_in', 'takeaway', 'delivery')", name=op.f('ck_orders_valid_order_type')),
    sa.CheckConstraint("status in ('open', 'completed', 'void')", name=op.f('ck_orders_valid_order_status')),
    sa.CheckConstraint('delivery_charge >= 0', name=op.f('ck_orders_delivery_charge_nonneg')),
    sa.CheckConstraint('discount_value >= 0', name=op.f('ck_orders_discount_value_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_orders_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_orders_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['server_id'], ['users.id'], name=op.f('fk_orders_server_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_orders_table_id_tables'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_branch_status', ['branch_id', 'status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('service_charge_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('delivery_charge_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='unpaid', nullable=False),
    sa.Column('cogs_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('print_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('unpaid', 'partial', 'paid')", name=op.f('ck_invoices_valid_sale_invoice_status')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_invoices_sale_invoice_total_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_invoices_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number')),
    sa.UniqueConstraint('order_id', name=op.f('uq_invoices_order_id'))
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('discount_kind', sa.String(length=10), server_default='none', nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.CheckConstraint("discount_kind in ('none', 'percentage', 'fixed')", name=op.f('ck_order_lines_valid_line_discount_kind')),
    sa.CheckConstraint('discount_value >= 0', name=op.f('ck_order_lines_line_discount_value_nonneg')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_lines_positive_line_qty')),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_order_lines_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_lines_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    op.create_table('order_line_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_order_line_modifiers_order_line_id_order_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_line_modifiers'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method in ('cash', 'card', 'bank_transfer', 'mobile_wallet', 'other')", name=op.f('ck_payments_valid_payment_method')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_positive_payment')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_payments_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_register_sessions.id'], name=op.f('fk_payments_cash_session_id_cash_register_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_payments_received_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate_pct', sa.Numeric(precision=9, scale=4), nullable=True))


    # cash_movements is an append-only ledger, like audit_logs / stock_movements / supplier_ledger_entries.
    op.execute("""
        CREATE TRIGGER trg_cash_movements_immutable
        BEFORE UPDATE OR DELETE ON cash_movements
        FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable();
    """)

    # Only one OPEN order may reference a given table at a time (enforced at the DB level, not
    # just in the service layer, since it protects against concurrent double-seating).
    op.execute("""
        CREATE UNIQUE INDEX uq_orders_one_open_per_table
        ON orders (table_id) WHERE status = 'open' AND table_id IS NOT NULL;
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP INDEX IF EXISTS uq_orders_one_open_per_table')
    op.execute('DROP TRIGGER IF EXISTS trg_cash_movements_immutable ON cash_movements')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('tax_rate_pct')

    op.drop_table('payments')
    op.drop_table('order_line_modifiers')
    op.drop_table('order_lines')
    op.drop_table('invoices')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_branch_status')

    op.drop_table('orders')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_session_id'))

    op.drop_table('cash_movements')
    op.drop_table('tables')
    op.drop_table('product_modifiers')
    op.drop_table('cash_register_sessions')
    op.drop_table('floors')
    op.drop_table('customers')
    # ### end Alembic commands ###
