"""kitchen: stations, tickets, item station, order line fired flag

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 12:37:53.720528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_kitchen_stations_branch_id_branches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kitchen_stations')),
    sa.UniqueConstraint('branch_id', 'name', name='uq_station_branch_name')
    )
    op.create_table('kitchen_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='queued', nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('fired_by', sa.Integer(), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority in ('normal', 'rush')", name=op.f('ck_kitchen_tickets_valid_ticket_priority')),
    sa.CheckConstraint("status in ('queued', 'preparing', 'ready', 'served', 'cancelled')", name=op.f('ck_kitchen_tickets_valid_ticket_status')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_kitchen_tickets_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fired_by'], ['users.id'], name=op.f('fk_kitchen_tickets_fired_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_kitchen_tickets_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['kitchen_stations.id'], name=op.f('fk_kitchen_tickets_station_id_kitchen_stations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kitchen_tickets')),
    sa.UniqueConstraint('ticket_number', name=op.f('uq_kitchen_tickets_ticket_number'))
    )
    with op.batch_alter_table('kitchen_tickets', schema=None) as batch_op:
        batch_op.create_index('ix_kitchen_tickets_branch_status', ['branch_id', 'status'], unique=False)
        batch_op.create_index('ix_kitchen_tickets_station_status', ['station_id', 'status'], unique=False)

    op.create_table('kitchen_ticket_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_kitchen_ticket_lines_order_line_id_order_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['kitchen_tickets.id'], name=op.f('fk_kitchen_ticket_lines_ticket_id_kitchen_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kitchen_ticket_lines')),
    sa.UniqueConstraint('order_line_id', name=op.f('uq_kitchen_ticket_lines_order_line_id'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inventory_items_station_id_kitchen_stations'), 'kitchen_stations', ['station_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fired', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_column('is_fired')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_items_station_id_kitchen_stations'), type_='foreignkey')
        batch_op.drop_column('station_id')

    op.drop_table('kitchen_ticket_lines')
    with op.batch_alter_table('kitchen_tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_kitchen_tickets_station_status')
        batch_op.drop_index('ix_kitchen_tickets_branch_status')

    op.drop_table('kitchen_tickets')
    op.drop_table('kitchen_stations')
    # ### end Alembic commands ###
